let tiles = 
[[
    {flipped: false, word:"black", image:'./Cards/Colors/black.jpeg'},
    {flipped: false, word:"blue", image:'./Cards/Colors/blue.jpeg'},
    {flipped: false, word:"brown", image:'./Cards/Colors/brown.jpeg'},
    {flipped: false, word:"green", image:'./Cards/Colors/green.jpeg'},
    {flipped: false, word:"orange", image:'./Cards/Colors/orange.jpeg'},
    {flipped: false, word:"pink", image:'./Cards/Colors/pink.jpeg'},
    {flipped: false, word:"purple", image:'./Cards/Colors/purple.jpeg'},
    {flipped: false, word:"red", image:'./Cards/Colors/red.jpeg'},
    {flipped: false, word:"white", image:'./Cards/Colors/white.jpeg'},
    {flipped: false, word:"yellow", image:'./Cards/Colors/yellow.jpeg'}
],
[
    {flipped: false, word:"arrow", image:'./Cards/Shapes/arrow.jpg'},
    {flipped: false, word:"circle", image:'./Cards/Shapes/circle.jpg'},
    {flipped: false, word:"ellipse", image:'./Cards/Shapes/ellipse.jpg'},
    {flipped: false, word:"heart", image:'./Cards/Shapes/heart.jpg'},
    {flipped: false, word:"kite", image:'./Cards/Shapes/kite.jpg'},
    {flipped: false, word:"octagon", image:'./Cards/Shapes/octagon.jpg'},
    {flipped: false, word:"pentagon", image:'./Cards/Shapes/pentagon.jpg'},
    {flipped: false, word:"quatrefoil", image:'./Cards/Shapes/quatrefoil.jpg'},
    {flipped: false, word:"rectangle", image:'./Cards/Shapes/rectangle.jpg'},
    {flipped: false, word:"scalene", image:'./Cards/Shapes/scalene.jpg'},
    {flipped: false, word:"semicircle", image:'./Cards/Shapes/semicircle.jpg'},
    {flipped: false, word:"square", image:'./Cards/Shapes/square.jpg'},
    {flipped: false, word:"star", image:'./Cards/Shapes/star.jpg'},
    {flipped: false, word:"trefoil", image:'./Cards/Shapes/trefoil.jpg'},
    {flipped: false, word:"triangle", image:'./Cards/Shapes/triangle.jpg'},
],
[
    {word:'blank', image:'./Cards/Emoties/blank.jpeg'},
    {word:'blowkiss', image:'./Cards/Emoties/blowkiss.jpeg'},
    {word:'boohoo', image:'./Cards/Emoties/boohoo.jpeg'},
    {word:'cool', image:'./Cards/Emoties/cool.jpeg'},
    {word:'cryinglaugh', image:'./Cards/Emoties/cryinglaugh.jpeg'},
    {word:'grin', image:'./Cards/Emoties/grin.jpeg'},
    {word:'groan', image:'./Cards/Emoties/groan.jpeg'},
    {word:'grumble', image:'./Cards/Emoties/grumble.jpeg'},
    {word:'harhar', image:'./Cards/Emoties/harhar.jpeg'},
    {word:'kissy', image:'./Cards/Emoties/kissy.jpeg'},
    {word:'love', image:'./Cards/Emoties/love.jpeg'},
    {word:'meh', image:'./Cards/Emoties/meh.jpeg'},
    {word:'no', image:'./Cards/Emoties/no.jpeg'},
    {word:'oops', image:'./Cards/Emoties/oops.jpeg'},
    {word:'proud', image:'./Cards/Emoties/proud.jpeg'},
    {word:'sweating', image:'./Cards/Emoties/sweating.jpeg'},
    {word:'tired', image:'./Cards/Emoties/tired.jpeg'},
    {word:'uh', image:'./Cards/Emoties/uh.jpeg'},
    {word:'wah', image:'./Cards/Emoties/wah.jpeg'},
    {word:'whoa', image:'./Cards/Emoties/whoa.jpeg'},
    {word:'wink', image:'./Cards/Emoties/wink.jpeg'},
    {word:'winkwink', image:'./Cards/Emoties/winkwink.jpeg'},
    {word:'yay', image:'./Cards/Emoties/yay.jpeg'},
    {word:'yikes', image:'./Cards/Emoties/yikes.jpeg'}
]
]

export {tiles}